name: Publishes a new package of Zebble.Billing to the nuget.org
on:
  push:
    branches: [ master ]
jobs:
  build_server:
    strategy:
      matrix:
        configuration: [ Release ]
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install Zebble's CLI tools
      run: dotnet tool install --global zebble-build

    - name: Publish a new Zebble.Billing.Server package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server
      continue-on-error: true

    - name: Publish a new Zebble.Billing.Server.AppStore package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.AppStore
      continue-on-error: true

    - name: Publish a new Zebble.Billing.Server.GooglePlay package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.GooglePlay
      continue-on-error: true

    - name: Publish a new Zebble.Billing.Server.CafeBazaar package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.CafeBazaar
      continue-on-error: true

    - name: Publish a new Zebble.Billing.Server.Huawei package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.Huawei
      continue-on-error: true

    - name: Publish a new Zebble.Billing.Server.DynamoDb package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.DynamoDb
      continue-on-error: true

    - name: Publish a new Zebble.Billing.Server.EntityFramework package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.EntityFramework
      continue-on-error: true

    - name: Publish a new Zebble.Billing.Server.Voucher package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.Voucher
      continue-on-error: true

    - name: Publish a new Zebble.Billing.Server.Voucher.DynamoDb package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.Voucher.DynamoDb
      continue-on-error: true

    - name: Publish a new Zebble.Billing.Server.Voucher.EntityFramework package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.Voucher.EntityFramework
      continue-on-error: true