name: Publishes a new package of Zebble.Billing to the nuget.org
on:
  push:
    branches: [ master ]
jobs:
  build_client:
    strategy:
      matrix:
        configuration: [ Release ]
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install MAUI
      run: dotnet workload install ios android maui --source https://aka.ms/dotnet8/nuget/index.json --source https://api.nuget.org/v3/index.json

    - name: Install Zebble's CLI tools
      run: dotnet tool install --global zebble-build

    - name: Publish a new Zebble.Billing.Plugin package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Plugin

    - name: Publish a new Zebble.Billing.Plugin.CafeBazaar package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish --configuration ReleaseCafeBazaar
      working-directory: Billing.Plugin

    - name: Publish a new Zebble.Billing.Plugin.Huawei package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish --configuration ReleaseHuawei
      working-directory: Billing.Plugin

  build_server:
    strategy:
      matrix:
        configuration: [ Release ]
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install Zebble's CLI tools
      run: dotnet tool install --global zebble-build

    - name: Publish a new Zebble.Billing.Server package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server

    - name: Publish a new Zebble.Billing.Server.AppStore package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.AppStore

    - name: Publish a new Zebble.Billing.Server.GooglePlay package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.GooglePlay

    - name: Publish a new Zebble.Billing.Server.CafeBazaar package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.CafeBazaar

    - name: Publish a new Zebble.Billing.Server.Huawei package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.Huawei

    - name: Publish a new Zebble.Billing.Server.DynamoDb package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.DynamoDb

    - name: Publish a new Zebble.Billing.Server.EntityFramework package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.EntityFramework

    - name: Publish a new Zebble.Billing.Server.Voucher package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.Voucher

    - name: Publish a new Zebble.Billing.Server.Voucher.DynamoDb package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.Voucher.DynamoDb

    - name: Publish a new Zebble.Billing.Server.Voucher.EntityFramework package
      run: zebble-build update-plugin --api-key ${{secrets.NUGET_API_KEY}} --publish
      working-directory: Billing.Server.Voucher.EntityFramework